# Generated by Django 3.0.3 on 2020-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'manager'), (3, 'employee')], null=True),
        ),
    ]
